version: '3.4'

services:
  user_save_project:
    image: usersaveproject:dev
    container_name: User_Save_Project
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "User_Save_Project"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/basarcelebi/Projects/UserSaveProject/User_Save_Project/User_Save_Project:/app
      - /Users/basarcelebi/Projects/UserSaveProject/User_Save_Project:/src
      - /Users/basarcelebi/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/basarcelebi/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/User_Save_Project.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true